/** Official topic pages provide stable entry points when a site's search endpoint is slow. */
const pages = [
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗/u, topic: /茶苗|種苗|苗木|育苗|扦插|定植|移植/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?func=1&id=24214&keyword=&type=12809" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗/u, topic: /乾旱|失水|灌溉|根系|保水|覆蓋/u, url: "https://kmweb.moa.gov.tw/theme_data.php?id=54791&sub_theme=variety&theme=news" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗/u, topic: /修剪|台刈|旱害|枝條/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=7163" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗|茶餅病|茶小綠葉蟬/u, topic: /海拔|氣候|高山|坡向|陽坡|陰坡|坡度|土壤|乾旱|排水|透水|板結|酸鹼|有機質/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=7154" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗|茶餅病|茶小綠葉蟬/u, topic: /海拔|高山/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=419436" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗|茶餅病|茶小綠葉蟬/u, topic: /基肥|追肥|施肥|肥料|栽培|肥培|肥傷/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=7155" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗|茶餅病|茶小綠葉蟬/u, topic: /基肥|追肥|施肥|肥料/u, url: "https://kmweb.moa.gov.tw/techcd/作物病蟲害與肥培管理技術資料/特作/茶樹/肥培/茶樹-肥培.htm" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗/u, topic: /施肥|肥料|肥培|土壤檢測|土壤分析/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?func=1&id=26390&type=13204" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗/u, topic: /板結|透水|排水|根群/u, url: "https://kmweb.moa.gov.tw/theme_data.php?id=54800&sub_theme=variety&theme=news" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗|茶餅病|茶小綠葉蟬/u, topic: /餅病/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=7393" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗|茶餅病|茶小綠葉蟬/u, topic: /小綠葉蟬|病蟲害|梅雨|防治/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=7156" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗|茶餅病|茶小綠葉蟬/u, topic: /小綠葉蟬/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=24824" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗|茶餅病|茶小綠葉蟬/u, topic: /小綠葉蟬/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=7398" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗|茶餅病|茶小綠葉蟬/u, topic: /小綠葉蟬.*(?:品質|茶菁)|(?:品質|茶菁).*小綠葉蟬/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=24247" },
  { crop: /甘藷|地瓜|番薯/u, topic: /整地|季節|栽培|採收|育苗|藷苗|種苗|插植|苗圃|種藷|作畦/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=19318" },
  { crop: /甘藷|地瓜|番薯/u, topic: /雜草|除草|中耕|培土|插苗|栽植|藤蔓|塊根形成/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=19318" },
  { crop: /甘藷|地瓜|番薯/u, topic: /排水|灌溉|畦溝|土壤水分/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=19320" },
  { crop: /甘藷|地瓜|番薯/u, topic: /整地|作畦|畦高|排水|塊根/u, url: "https://kmweb.moa.gov.tw/knowledge_view.php?id=13729" },
  { crop: /甘藷|地瓜|番薯/u, topic: /施肥|氮|磷|鉀|基肥|追肥|肥培|養分/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=19319" },
  { crop: /甘藷|地瓜|番薯/u, topic: /病蟲害|蟻象|採收|線蟲/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=19321" },
  { crop: /甘藷|地瓜|番薯/u, topic: /葉片.*(?:啃食|幼蟲|蛀孔)|誘捕|輪作|花葉|莖基部|軟腐/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=19321" },
  { crop: /甘藷|地瓜|番薯/u, topic: /採收|採後|貯藏|腐爛|破皮|傷口/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=19322" },
  { crop: /甘藷|地瓜|番薯/u, topic: /補植|缺株|苗尖|苗株|存活|風災|颱風|災後/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=19358" },
  { crop: /甘藷|地瓜|番薯/u, topic: /蟻象/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=7757" },
  { crop: /甘藷|地瓜|番薯/u, topic: /蟻象/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=12883" },
  { crop: /香菇/u, topic: /段木|太空包|栽培/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=35701" },
  { crop: /香菇/u, topic: /太空包|養分|出菇|溫濕度|綠黴|木黴|培養基|碳酸鈣|木屑|米糠|輔料|接種|菌絲|走菌|滅菌/u, url: "https://kmweb.moa.gov.tw/theme_data.php?id=54519&sub_theme=variety&theme=news" },
  { crop: /香菇/u, topic: /太空包|裝袋|菌絲|接種|滅菌|木屑|污染|通氣/u, url: "https://kmweb.moa.gov.tw/theme_data.php?id=55012&sub_theme=agri_life&theme=news" },
  { crop: /香菇/u, topic: /綠黴|木黴|污染|防治|雜菌|青包/u, url: "https://kmweb.moa.gov.tw/theme_data.php?id=54903&sub_theme=variety&theme=news" },
  { crop: /香菇/u, topic: /太空包|養分|培養基|碳酸鈣|木屑|米糠|輔料|接種|菌絲|走菌|滅菌/u, url: "https://kmweb.moa.gov.tw/theme_data.php?id=55135&sub_theme=variety&theme=news" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /株距|行距|種植/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=30734" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /灌溉|水分|乾季|淹水|排水|土壤/u, url: "https://kmweb.moa.gov.tw/theme_data.php?id=54411&sub_theme=variety&theme=news" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /果房|疏果|果指|果軸|採收|成熟度|包裝/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=283699" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /株距|行距|種植|密度|三角形/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=11046" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /施肥|基肥|追肥|肥料|肥培|鉀|抽穗/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=288346" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /施肥|基肥|追肥|肥料|肥培|鉀|抽穗/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=11049" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /黃葉病|鐮刀菌|枯萎病/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=30640" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /黃葉病|鐮刀菌|枯萎病/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=30528" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /黃葉病|鐮刀菌|枯萎病/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=11160" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /黑星病|防治/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=30671" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /黑星病/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=11161" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /套袋/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=283699" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /套袋/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=11157" },
  // Curated, live HTML articles for post-harvest and environment-management gaps.
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗|茶菁/u, topic: /茶菁|鮮葉|採後|採收後|運送|運輸|堆積|紅化|儲運/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=53669" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗/u, topic: /枯梢|枝枯|葉片褐化|茶苗|補植/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=7390" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗/u, topic: /高溫多濕|通風|排水|病蟲害監測/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=24188" },
  { crop: /高山茶|茶樹|茶園|茶葉|茶苗/u, topic: /害蟲|蟲害|監測|蟲咬|受害|診斷/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=241168" },
  { crop: /甘藷|地瓜|番薯/u, topic: /採收|採後|貯藏|儲藏|破皮|損傷|癒傷|分級|腐爛/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=423333" },
  { crop: /甘藷|地瓜|番薯/u, topic: /苗圃|種苗|病毒|斑駁|基腐|病徵|送驗|驗證/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=415972" },
  { crop: /甘藷|地瓜|番薯/u, topic: /輪作|連作|水稻|水田|基腐/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=381379" },
  { crop: /香菇/u, topic: /出菇|走菌|潮次|乾裂|通風|濕度|烘乾|乾燥|採後|採收後|分級/u, url: "https://kmweb.moa.gov.tw/theme_data.php?id=55135&sub_theme=variety&theme=news" },
  { crop: /香菇/u, topic: /烘乾|乾燥|含水|分級|菇體/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=35701" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /強風|風吹|防風|支柱|支撐|倒伏/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=30734" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /強風|風吹|葉裂|折葉|支柱|支撐|倒伏/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=318328" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /豪雨|積水|低窪|缺氧|風災|水災|折葉|施肥/u, url: "https://kmweb.moa.gov.tw/theme_data.php?id=53021&sub_theme=agri_life&theme=news" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /乳汁|分梳|分把|擦傷|壓傷|採後|採收後|選別|降溫/u, url: "https://kmweb.moa.gov.tw/knowledgebase.php?id=283699" },
  { crop: /香蕉|蕉園|蕉株|蕉苗|蕉果/u, topic: /除草|雜草|草生|覆蓋|淺根/u, url: "https://kmweb.moa.gov.tw/subject/subject.php?id=11195" },
] as const;

export function officialPageUrlsForQuestion(question: string, domain: string) {
  if (domain.toLowerCase() !== "kmweb.moa.gov.tw") return [];
  return [...new Set(pages.filter(page => page.crop.test(question) && page.topic.test(question)).map(page => page.url))];
}
